media: public/images
content:
  - name: pages
    label: Pages
    type: collection
    path: docs
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: tags
        label: Tags (Sentence case, surround multiple tags with square brackets [Like, This])
        type: string
      - name: applies_to
        Laben: Applies to
        type: string
      - name: author
        label: Author
        type: string
      - name: admin_required
        label: Admin required
        type: boolean
      - name: no_pdf
        label: No PDF (don't generate PDF)
        type: boolean
      - name: status
        label: Status
        type: select
        options:
          values: [in_progress, draft, published]
      - name: layout
        label: Layout
        type: string
        options:
          default: xml_freshdesk.liquid
      - name: body
        type: rich-text