media: public/images # comment?
content:
  - name: pages
    label: Pages
    type: collection
    path: docs
    fields:
      - name: title
        label: Title (with text)
        type: string
      - name: description
        type: string
      - name: tags
        type: string
      - name: applies_to
        type: string
      - name: author
        type: string
      - name: admin_required
        type: boolean
      - name: no_pdf
        type: boolean
      - name: status
        type: select
        options:
          values: [in_progress, draft, published]
      - name: layout
        type: string
        options:
          default: xml_freshdesk.liquid
      - name: body
        type: rich-text